### ISSUE TITLE
trouble when upgrading react-native to > 0.44

### ISSUE THREAD

**Issue by RebeccaAouizerats** [derniercri/react-components#1]
`react-native-maps` v 0.13.1 doesn't fit with the `react-native` >= 0.44:

![pasted image at 2017_07_17 09_35 am](https://user-images.githubusercontent.com/23192988/28610413-edbf0d04-71f0-11e7-973c-c1fc3bbdfe06.png)

When upgrading the `react-native-maps` to 0.15.3 in the root node_modules folder i get:

![image](https://user-images.githubusercontent.com/23192988/28610452-13360b0a-71f1-11e7-87c5-c3dc6ffcad48.png)

the issue is that the version of `react-native-maps` in your package doesn't fit with the version of the one in the root node_modules folder. when copy and past the `react-component-maps` to your package (from the root), the issue was gone.

can you please upgrade the `react-component-maps` to 1.15.3?
thanks

**Comment by havenS** [comment]
@RebeccaAouizerats I updated it. In fact, even updated the error still occured. I had to remove the dependency from `react-field-components`.
Simply run `yarn upgrade react-field-components` and it will be ok, it worked for me.

**Comment by RebeccaAouizerats** [comment]
thanks!
